### ISSUE TITLE
How to obtain training data？

### ISSUE THREAD

**Issue by 17701311118** [kappazeta/cm_predict#21]

**Comment by tanyashtym** [comment]
Hey!

Thank you for your question!
We are currently uploading the dataset for global conditions to Zenodo. As soon as it is available, we will inform you.

However, you could try out the dataset we labelled for the Northern Europe terrestrial summer conditions: https://zenodo.org/record/5095024

**Comment by 17701311118** [comment]
> 
Hey!

Thank you for your dataset and working.

**Comment by tanyashtym** [comment]
Hey!

You can find the full KappaSet here: https://zenodo.org/record/7100327
