### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by kanlions** [kappazeta/cm_predict#23]
I observe that in data generator python file there are separate normalization for UNET and Deeplab V3+. Can you please tell me how those values are generated?

**Comment by tanyashtym** [comment]
Hi!

Normalisation parameters were calculated for each band over the entire training set. You can find the code here: https://github.com/kappazeta/cloudmask-fit/blob/master/cm_fit/training/train_utils.py  

The normalisation parameters for U-Net were calculated for the dataset that covers only terrestrial North European summer conditions. You can find more information here: https://www.mdpi.com/2072-4292/13/20/4100
In turn, we used KappaSet (https://zenodo.org/record/7100327) to train the DeepLabv3+. Therefore, normalisation parameters were calculated through the KappaSet's training set.

If you have more questions, feel free to ask!

**Comment by indrek-sunter** [comment]
Closing, for there have not been any more questions.
